common:
  app: getting-started
  shortname: getstarted
  team: plattform
  ingress:
    trafficType: public
  container:
    image: <+artifacts.primary.image>
    cpu: 0.006
    memory: 78
  secrets:
    app-secrets:
      - API_TOKEN # Read API_TOKEN from Google Secret Manager 
